In [1]:
import numpy as np

In [2]:
val1=np.array([12,45,10.40,44])

In [3]:
val1

array([12. , 45. , 10.4, 44. ])

In [4]:
type(val1)

numpy.ndarray

In [5]:
val1.shape

(4,)

In [6]:
val1.dtype

dtype('float64')

In [7]:
val2 = np.arange(0,52,2)

In [8]:
val2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [12]:
val3 = np.ones((1,6) , dtype = int)

In [13]:
val3

array([[1, 1, 1, 1, 1, 1]])

In [14]:
val4 =  np.random.randint(3,30,size=(4,6))

In [15]:
val4

array([[18, 25, 12, 11, 19,  7],
       [19, 15, 25, 12, 11, 20],
       [25,  9, 28,  7, 24, 19],
       [19, 22, 13,  4,  3, 17]])

In [16]:
a = (10,2)
b = (20,5)

In [17]:
np. divide (a,b)

array([0.5, 0.4])

In [18]:
np. multiply (a,b)

array([200,  10])

In [19]:
np. add (a,b)

array([30,  7])

In [21]:
np.subtract (a,b)

array([-10,  -3])

In [22]:
a1 = np.array([[11,12,13],[14,15,16]])
print(a1.shape)

(2, 3)
